import React, { useState } from 'react';
import { DataTable } from 'primereact/datatable';
import { Column } from 'primereact/column';
import { Panel } from 'primereact/panel';

const initialOrders = [
    {
        sNo: { number: '1' },
        name: 'Nema 17 48mm stepper motor',
        uniwareSKU: {
            name: 'TIFMC00B0',
        },
        quantity: {
            number: '5',
        },
        shelfCode: {
            name: '',
        },
        batchCode: {
            name: '',
        },
        inventoryType: 'Good_Inventory',
        orderType: 1,
    },
];

export default function SampleFormDemo() {
    const [orders, setOrders] = useState(initialOrders);
    const [activeIndex, setActiveIndex] = useState(0);

    const items = [{ label: 'Pending' }, { label: 'Completed' }];
    return (
        <div className="grid p-3">
            <div className="col-8">
                <div className="grid grid-nogutter">
                    <div className="col-12">
                        <div className="card">
                            <DataTable
                                value={orders}
                                // style={{ minWidth: '50rem' }}
                                showGridlines
                                stripedRows
                            >
                                <Column field="sNo.number" header="S No." />
                                <Column field="name" header="Name" />
                                <Column field="uniwareSKU.name" header="Uniware SKU" />
                                <Column field="quantity.number" header="Quantity" />
                                <Column field="shelfCode.name" header="Shelf Code" />
                                <Column field="batchCode.name" header="Batch Code" />
                                <Column field="inventoryType" header="Inventory Type" />
                            </DataTable>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="card">
                            Putaway summary
                        </div>
                    </div>
                </div>
            </div>


            <div className="col-4">
                <div className="card">
                    <Panel header="General Information">
                        <table className="grid-table">
                            <thead>
                                <tr>
                                    <td><b>Putaway Number</b> </td><td>PT1285</td>
                                </tr>
                                <tr>
                                    <td><b>Type </b></td> <td> PUTAWAY_REVERSE_PIC</td>
                                </tr>
                                <tr>
                                    <td><b>Total Items </b> </td> <td> 5</td>
                                </tr>
                                <tr>
                                    <td><b>Status</b></td> <td> CREATED</td>
                                </tr>
                                <tr>
                                    <td><b>Generated By </b> </td> <td>likithjwramesh@gmail.com</td>
                                </tr>
                                <tr>
                                    <td><b>Created At </b></td><td>12/10/2022</td>
                                </tr>
                            </thead>
                        </table>
                    </Panel>
                </div>
            </div>
        </div>
    );
}
